### ISSUE TITLE
Unable to convert video to image

### ISSUE THREAD

**Issue by IamExperimenting** [AbhishekSalian/Video2Images#2]
from video2images import Video2Images
import time
start_time = time.time()

Video2Images(video_filepath="/home/ComputerVision/tfrecords/My Movie 49.mov", out_dir="/home/ComputerVision/tfrecords/image/")
print("--- %s seconds ---" % (time.time() - start_time))

Error:
Traceback (most recent call last):
  File "video2image.py", line 38, in <module>
    Video2Images(video_filepath="/home/ComputerVision/tfrecords/My Movie 49.mov", out_dir="/home/ComputerVision/tfrecords/image/")
  File "/home/miniconda3/lib/python3.7/site-packages/video2images/video2images.py", line 127, in __init__
    video_duration, vformat = self.__getDuration()
  File "/home/miniconda3/lib/python3.7/site-packages/video2images/video2images.py", line 171, in __getDuration
    video = moviepy.editor.VideoFileClip(self.video_filepath)
  File "/home/miniconda3/lib/python3.7/site-packages/moviepy/video/io/VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "/home/miniconda3/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 36, in __init__
    fps_source)
  File "/home/miniconda3/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 259, in ffmpeg_parse_infos
    infos = error.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 1506: invalid start byte

**Comment by AbhishekSalian** [comment]
Is the video path correctly given?

**Comment by AbhishekSalian** [comment]
"/home/ComputerVision/tfrecords/My Movie 49.mov" -> "/home/ **___something is missing in here___**/ComputerVision/tfrecords/My Movie 49.mov" Please check back once again

**Comment by IamExperimenting** [comment]
Yes, I did remove it intensionally. Not to share the original path. But then, it's fine. 

Here is the code:

from video2images import Video2Images
Video2Images(video_filepath="/home/falconheavy/ComputerVision/tfrecords/ffmpeg/MyMovie49.mov",
             out_dir="/home/falconheavy/ComputerVision/tfrecords/image/")

ERROR:
Traceback (most recent call last)
  File "video2image.py", line 5, in <module>
    out_dir="/home/falconheavy/ComputerVision/tfrecords/image/")
  File "/home/falconheavy/miniconda3/envs/TFDev/lib/python3.7/site-packages/video2images/video2images.py", line 127, in __init__
    video_duration, vformat = self.__getDuration()
  File "/home/falconheavy/miniconda3/envs/TFDev/lib/python3.7/site-packages/video2images/video2images.py", line 171, in __getDuration
    video = moviepy.editor.VideoFileClip(self.video_filepath)
  File "/home/falconheavy/miniconda3/envs/TFDev/lib/python3.7/site-packages/moviepy/video/io/VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "/home/falconheavy/miniconda3/envs/TFDev/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 36, in __init__
    fps_source)
  File "/home/falconheavy/miniconda3/envs/TFDev/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 259, in ffmpeg_parse_infos
    infos = error.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 1511: invalid start byte

**Comment by AbhishekSalian** [comment]
Seems like the video file is missing some information in it can you check with some other sample video.

**Comment by IamExperimenting** [comment]
@AbhishekSalian It worked with another video, but not the first one. Thanks very much for your response. :)

**Comment by AbhishekSalian** [comment]
Glad it worked. 1st video might be having some codec issue so ffmpeg cannot decode that.  Thanks for reaching out. if you come up with some solution for 1st video problem do create a merge request will review and merge. Once again thanks for cooperating. :)
